
experiment:
  name: state_punishment_beta
  epochs: 2000000
  max_turns: 100
  epsilon_decay: 0.0001

env:
  height: 15
  width: 15
  layers: 1
  channels: 9
  default_object: EmptyObject
  full_mdp: False # Whether to return the full agent # the result is not normal when True
  tile_size: [16, 16] # Default sprite size for visualization (not used as model input yet) [16, 16]
  prob:
    item_spawn: 0.2 # 0.1 #0.15 # Initial item spawn rate. Later rate is lower as otherwise the entire map gets overwhelmed.
    # item_choice: [0.1, 0.3, 0.4, 0.2] # gem, coin, food, bone
    item_choice: [0.5, 0.5, 0.0] # [0.3, 0.7] [0.8, 0.2]
    respawn_rate: 0.05

state_sys:
  prob_list: 
    Gem: 0.0
    Coin: 1.0
    Bone: 0.
  init_prob: 0.
  magnitude: 20  # 20 # positive - punishment, negative - reward 
  taboo: ['Coin']
  change_per_vote: 0.25

model:
  iqn:
    type: iRainbowModel
    num: 3
    device: cpu
    parameters:
      state_size: [6, 9, 7, 7] # If full_mdp is True, this is [channels, height, width]. If not, this is [channels, 2 * vision + 1, 2 * vision + 1]
      extra_percept_size: 2 # added for extra percept
      action_size: 6
      layer_size: 250 # 250
      num_frames: 5
      n_step: 3
      BATCH_SIZE: 64
      BUFFER_SIZE: 1024
      LR: 0.00025
      TAU: .001
      GAMMA: 0.99
      N: 12
      sync_freq: 200
      model_update_freq: 4
      epsilon: 0.01

agent:
  agent:
    num: 3
    model: iqn
    num_memories: 5 # Should match num_frames in the model above
    vision: 3
    # appearance: (0.0, 0.0, 255.0)
    appearance: 
      - [0.0, 0.0, 255.0, 255.0, 0., 0.0, 0.0, 0.0, 0.0, ]
      - [0.0, 0.0, 255.0, 0., 255., 0.0, 0.0, 0.0, 0.0, ]
      - [0.0, 0.0, 255.0, 0.0, 0.0, 255., 0., 0.0, 0.0,]
      - [0.0, 0.0, 255.0, 0.0, 0.0, 0., 255., 0.0, 0.0, ]
      - [0.0, 0.0, 255.0, 0.0, 0., 0.0, 0., 255., 0.0, ]
      - [0.0, 0.0, 255.0, 0.0, 0., 0.0, 0., 0., 255.0, ]
      - [0.0, 0.0, 255.0, 0.0, 0., 0.0, 0., 0., 0.0, 255.]
    memory_size: 100 # If this is larger than max_turns above, could cause issues
    # Not used right now
    tile_size: (1, 1)
    pov_size: 9
    health: 10
    extra_percept_size: 2 # added for extra percept

entity:
  Gem:
    start_num: 1
    value: 5 # 10
    appearance: (0.0, 255.0, 0.0) # Green
    social_harm: 0
  Coin:
    start_num: 1
    value: 10 # 2 #10
    appearance: (255.0, 0.0, 0.0) # Yellow
    social_harm: 40 # 5
  # Food:
  #   start_num: 0
  #   value: 1
  #   appearance: (255.0, 0.0, 0.0) # Red
  Bone:
    start_num: 1
    value: 10
    appearance: (0, 0, 0) # Black
    social_harm: 40 # 5

# Not used right now
replay:
  use_sprites: False
  save: True
  replay_frequency: 500
  num_replays: 3
  end_update: True
  epsilon: 0.01
  blit: False
  fps: 2
  turns: 100

# Root folder for accessing file structure and modules
root: '/Users/socialai2/Documents/agentarium_state_punishment'
log: True
state_mode: 'composite'
action_mode: 'simple'
# exp_name: "fixed_punishment_rate_0.75_twoAs_extra_percept_v2_higher_harm_gem_has_value_save_model" #'sanity_check_state_reward'
exp_name: 'test_punishment_noncomposite_oneA_po' #"test_composite_input_fixed_punishment_1.0_clear_detection_v0_oneA_instant_only_coin_hs500"
exp_name: 'test_voting_stacked_view_simple_actions_3agents_lifelong_005_v0' 
# stacked_views,single_view